language: php
php:
  - '5.6'
  - '7.0'
  - hhvm # on Trusty only
  - nightly

before_script:
  - composer self-update
  - composer install --prefer-source --no-interaction --dev

script: phpunit tests